#include<stdio.h>
//Tema do desafio
int main(){
    printf("DESAFIO SUPER TRUNFO: PAÍSES\n");

 //Nome do país
    printf("BRASIL\n");
    printf("ESTADOS DO BRASIL\n");

    //CADASTRANDO AS CARTAS DOS ESTADOS
    printf("RIO DE JANEIRO;SÃO PAULO;MINAS GERAIS;ESPÍRITO SANTO;GOIÁS;SANTA CATARINA;BAHIA E PERNAMBUCO\n");

    //CADASTRANDO AS CARTAS DA CIDADE DO RIO DE JANEIRO
    printf("ESTADO RIO DE JANEIRO= CIDADES: VALENÇA, VOLTA REDONDA, BARRA DO PIRAÍ E VASSOURAS\n ");

    //CADASTRANDO AS CARTAS DA CIDADE DE SÃO PAULO
    printf("ESTADO SÃO PAULO= CIDADES: APARECIDA, SÃO VICENTE, CAMPINAS E SÃO PAULO\n");

    //CADASTRANDO AS CARTAS DA CIDADE DE MINAS GERAIS
    printf("ESTADO MINAS GERAIS= CIDADES: BELO HORIZONTE, UBERLÂNDIA, JUÍZ DE FORA E OURO PRETO\n");

    //CADASTRANDO AS CARTAS DA CIDADE DO ESPÍRITO SANTO
    printf("ESTADO ESPÍRITO SANTO=CIDADES: VITÓRIA, SERRA, GUARAPARI E VILA VELHA\n");

    //CADASTRANDO AS CARTAS DA CIDADE DE GOIÁS
    printf("ESTADO GOIÁS=CIDADES: CORUMBÁ DE GOIÁS, GOIÂNIA, PILAR DE GOIÁS E PIRENÓPOLIS\n");

    //CADASTRANDO AS CARTAS DA CIDADE DE SANTA CATARINA
    printf("ESTADO SANTA CATARINA= CIDADES:JOINVILLE, FLORIANÓPOLIS, BLUMENAU E SÃO JOSÉ\n");

    //CADASTRANDO AS CARTAS DA CIDADE DA BAHIA
    printf("ESTADO BAHIA= CIDADES:SALVADOR, FEIRA DE SANTANA, VITÓRIA DA CONQUISTA E ILHÉUS\n");

    //CADASTRANDO AS CARTAS DA CIDADE DE PERNAMBUCO
    printf("ESTADO PERNAMBUCO=CIDADES: RECIFE, JAPOATÃO DOS GUARARAPES, PETROLINA E CARUARU\n");

}