#include<stdio.h>
//Tema do desafio
int main(){
    printf("DESAFIO SUPER TRUNFO: PAÍSES\n");

 //Nome do país
    printf("BRASIL\n");

    //CADASTRANDO AS CARTAS DOS ESTADOS
    printf("RIO DE JANEIRO;SÃO PAULO;MINAS GERAIS;ESPÍRITO SANTO;GOIÁS;SANTA CATARINA;BAHIA E PERNAMBUCO\n");

    //CADASTRANDO AS CARTAS DA CIDADE DO RIO DE JANEIRO
    printf("ESTADO RIO DE JANEIRO= VALENÇA, VOLTA REDONDA, BARRA DO PIRAÍ E VASSOURAS\n ");
    //CADASTRANDO AS CARTAS DA CIDADE DE SÃO PAULO
    printf("ESTADO SÃO PAULO= APARECIDA, SÃO VICENTE, CAMPINAS E SÃO PAULO\n");
    //CADASTRANDO AS CARTAS DA CIDADE DE MINAS GERAIS
    printf("ESTADO MINAS GERAIS= BELO HORIZONTE, UBERLÂNDIA, JUÍZ DE FORA E OURO PRETO\n");
    //CADASTRANDO AS CARTAS DA CIDADE DO ESPÍRITO SANTO
    printf("ESTADO ESPÍRITO SANTO= VITÓRIA, SERRA, GUARAPARI E VILA VELHA\n");
    //CADASTRANDO AS CARTAS DA CIDADE DE GOIÁS
    printf("ESTADO GOIÁS= CORUMBÁ DE GOIÁS, GOIÂNIA, PILAR DE GOIÁS E PIRENÓPOLIS\n");
    //CADASTRANDO AS CARTAS DA CIDADE DE SANTA CATARINA
    printf("ESTADO SANTA CATARINA= JOINVILLE, FLORIANÓPOLIS, BLUMENAU E SÁO JOSÉ\n");
    //CADASTRANDO AS CARTAS DA CIDADE DA BAHIA
    printf("ESTADO BAHIA= SALVADOR, FEIRA DE SANTANA, VITÓRIA DA CONQUISTA E ILHÉUS\n");
    //CADASTRANDO AS CARTAS DA CIDADE DE PERNAMBUCO
    printf("ESTADO PERNAMBUCO= RECIFE, JAPOATÃO DOS GUARARAPES, PETROLINA E CARUARU\n");
}